---
title: "Vegetation Height and TWi Correlation Analysis — Regional Scale"
author: "Ting Tan"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_align: 'center'
bibliography: literatures.bib  
latex_engine: xelatex
csl: apa.csl
---


```{r SetUp, include=FALSE, eval=TRUE}

knitr::opts_chunk$set(
  comment = "#>", echo = FALSE, fig.width = 10, message = FALSE, warning = FALSE
)

library(ggplot2)
library(dplyr)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
```
---

## Objective

To explore the global pattern of vegetation structure in relation to hillslope hydrology, this study investigates how **vegetation height (VEGH)** varies with the **topographic wetness index (TWI)** using a window-based spatial correlation approach.

---

```{r}
regA_info <- readRDS(here::here("data/df_samples_A.rds")) |>
  select(ends_with("label"), ends_with("min"), ends_with("max"))

# Calculate center coordinates
regA_info <- regA_info |>
  mutate(center_x = (xmin + xmax)/2,
         center_y = (ymin + ymax)/2)

# Load world map
world <- ne_countries(scale = "medium", returnclass = "sf")

# Plot with colored points and legend, all English labels
ggplot(data = world) +
  geom_sf(fill = "antiquewhite") +
  geom_point(data = regA_info, aes(x = center_x, y = center_y, color = strata_A_label), size = 3) +
  coord_sf(xlim = c(-180, 180), ylim = c(-90, 90), expand = FALSE) +
  labs(title = "Locations of Six Regions on the World Map",
       x = "Longitude",
       y = "Latitude",
       color = "Region") +
  theme_minimal() +
  theme(legend.position = "right")
```


```{r}
```

```{r}
```

```{r}
```
