---
title: "Regions selection for topographic effect analysis"
author: "Ting Tan"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_align: 'center'
bibliography: literatures.bib  
latex_engine: xelatex
csl: apa.csl
---


```{r SetUp, include=FALSE, eval=TRUE}

knitr::opts_chunk$set(
  comment = "#>", echo = FALSE, fig.width = 10, message = FALSE, warning = FALSE
)

library(terra)
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)
library(DataExplorer)
library(RColorBrewer)
library(rnaturalearth)
library(sf)

# Load configuration and functions
source(here::here("config.R"))

```


---

## Objective

To explore the global pattern of vegetation structure in relation to hillslope hydrology, this study investigates how **vegetation height (VEGH)** varies with the **topographic wetness index (TWI)** using a window-based spatial correlation approach.

---

```{r DataPre}
# Load resampled raster datasets (AI, TWI, fused)

ai_55km_r <- terra::rast(ai_55km_file) * 0.0001 # Multiply all values by 0.0001 to get original value
fused_55km_r <- terra::rast(fused_55km_file)
dem_sd_55km_r <- terra::rast(dem_sd_55km_path)
fpa_55km_r <- terra::rast(fpa_55km_path)
fvegh_55km_r <- terra::rast(fvegh_55km_path)

# Stack rasters into a single SpatRaster
stacked <- c(ai_55km_r,
             fused_55km_r,
             dem_sd_55km_r,
             fpa_55km_r,
             fvegh_55km_r)

# Use land polygons to remove ocean area with NA

# Load land polygons
land <- rnaturalearth::ne_countries(scale = 110, returnclass = "sf")
land_vect <- vect(land)

# Crop and mask raster to land
stacked_masked <- mask(crop(stacked, land_vect), land_vect)

plot(stacked_masked)

# Convert to data frame
df <- as.data.frame(stacked_masked, xy = TRUE, na.rm = TRUE)
colnames(df) <- c("lon", "lat", "ai", "fused", "relief", "fpa", "fvegh")

# Clean up
rm(ai_55km_r, fused_55km_r, dem_sd_55km_r, fpa_55km_r, fvegh_55km_r)
gc()

```


```{r DataOverview}
# Ploting
p_hg <- DataExplorer::plot_histogram(df)

# combine the plots
cp_hg <- patchwork::wrap_plots(p_hg)

# Save histogram plot
ggsave(
  filename = here::here("data/figures/04_variables_hg.png"),
  plot = cp_hg,
  width = 8,
  height = 6,
  dpi = 300,
  units = "in"
)
```

```{r Bin}
df_binned <- df |>

  # create bins
  mutate(
    ai_bin = cut(ai, breaks = quantile(ai, probs = seq(0, 1, 1/5)), include.lowest = TRUE),
    relief_bin = cut(relief, breaks = quantile(relief, probs = seq(0, 1, 1/3)), include.lowest = TRUE),
    abs_lat = abs(lat),
    abs_lat_bin = cut(abs_lat, breaks = quantile(abs_lat, probs = seq(0, 1, 1/5)), include.lowest = TRUE)
  ) |>

  # Fig. 6 Down Valley drainage
  mutate(strata_A = interaction(ai_bin, relief_bin, drop = TRUE)) |>

  # Fig. 6 Aspect difference
  mutate(strata_B = interaction(abs_lat_bin, relief_bin, drop = TRUE)) |>

  # Assign readable labels to each bin
  mutate(
    ai_label = case_when(
      ai_bin == levels(ai_bin)[1] ~ "very_dry",
      ai_bin == levels(ai_bin)[2] ~ "dry",
      ai_bin == levels(ai_bin)[3] ~ "moderate",
      ai_bin == levels(ai_bin)[4] ~ "humid",
      ai_bin == levels(ai_bin)[5] ~ "very_humid"
    ),
    relief_label = case_when(
      relief_bin == levels(relief_bin)[1] ~ "flat_relief",
      relief_bin == levels(relief_bin)[2] ~ "moderate_relief",
      relief_bin == levels(relief_bin)[3] ~ "rugged_relief"
    ),
    lat_label = case_when(
      abs_lat_bin == levels(abs_lat_bin)[1] ~ "low_latitude",
      abs_lat_bin == levels(abs_lat_bin)[2] ~ "relatively_low_latitude",
      abs_lat_bin == levels(abs_lat_bin)[3] ~ "mid_latitude",
      abs_lat_bin == levels(abs_lat_bin)[4] ~ "relatively_high_latitude",
      abs_lat_bin == levels(abs_lat_bin)[5] ~ "high_latitude"
    )
  ) |>

  # Combine text labels into new readable strata labels
  mutate(
    strata_A_label = paste0(ai_label, "_", relief_label),
    strata_B_label = paste0(lat_label, "_", relief_label)
  ) |>

  select(-ai_label, -relief_label, -lat_label)
```


```{r Filter}

df_filt <- df_binned |>

  # use only data where influence of humans on veg height is minimal
  filter(fused < 0.05, fpa > 0.9, fvegh > 0.8) |>
    # filter(fused < 0.05, fpa > 0.95) |>

  # Filter to retain only data that is in bins 1/2, 3, and 5 for MI and Lat.
  # and for bins 1 and 3 for relief

  filter(
    # retain only data that is in bins 1, 3, and 5
    ai_bin %in% levels(ai_bin)[c(2, 3, 5)], # bin 1 are too dry that has little fraction of vegetation
    # retain only data that is in bins 1 and 3
    relief_bin %in% levels(relief_bin)[c(1, 3)],
    # retain only data that is in bins 1, 3, and 5
    abs_lat_bin %in% levels(abs_lat_bin)[c(1, 3, 5)]
  )

```

```{r Sampling}
# Pick one region (coarse gridcell) representing all combination of bins.
# Should yield 6 samples

set.seed(999)

# for Fig. 6 Down Valley drainage
df_samples_A <- df_filt |>
  group_by(strata_A) |>
  sample_n(size = 1, replace = FALSE) |>
  mutate(
    xmin = lon - 0.25,
    xmax = lon + 0.25,
    ymin = lat - 0.25,
    ymax = lat + 0.25
  ) |>
  select(-starts_with("strata_B")) |>
  ungroup()

# for Fig. 6 Aspect difference
df_samples_B <- df_filt |>
  group_by(strata_B) |>
  sample_n(size = 1, replace = FALSE) |>
  mutate(
    xmin = lon - 0.25,
    xmax = lon + 0.25,
    ymin = lat - 0.25,
    ymax = lat + 0.25
  ) |>
  select(-starts_with("strata_A")) |>
  ungroup()


# Save the two data frames as RDS files
saveRDS(df_samples_A, here::here("data/df_samples_A.rds"))
saveRDS(df_samples_B, here::here("data/df_samples_B.rds"))
```

```{r gpkg}
# ---- regA
# load region infos
regA_info <- readRDS(here::here("data/df_samples_A.rds")) |>
  select(ends_with("label"), ends_with("min"), ends_with("max"))

regA_gpkg <- regA_info |>
  rowwise() |>
  mutate(geometry = list(st_polygon(list(matrix(
    c(xmin, ymin,
      xmin, ymax,
      xmax, ymax,
      xmax, ymin,
      xmin, ymin),
    ncol = 2, byrow = TRUE))))) |>
  st_as_sf(crs = 4326)

# 写入 gpkg 文件
st_write(regA_gpkg, here::here("data/regionA_boxes.gpkg"), delete_layer = TRUE)


# ---- regB
# load region infos
regB_info <- readRDS(here::here("data/df_samples_B.rds")) |>
  select(ends_with("label"), ends_with("min"), ends_with("max"))

regB_gpkg <- regB_info |>
  rowwise() |>
  mutate(geometry = list(st_polygon(list(matrix(
    c(xmin, ymin,
      xmin, ymax,
      xmax, ymax,
      xmax, ymin,
      xmin, ymin),
    ncol = 2, byrow = TRUE))))) |>
  st_as_sf(crs = 4326)

# 写入 gpkg 文件
st_write(regB_gpkg, here::here("data/regionB_boxes.gpkg"), delete_layer = TRUE)


```

```{r}

# Data overview
table(df_binned$strata_A_label)
table(df_binned$strata_B_label)

table(df_filt$strata_A_label)
table(df_filt$strata_B_label)

table(df_samples_A$strata_A_label)
table(df_samples_B$strata_B_label)

# check the bins and the combinations
table(df_binned$ai_bin)
table(df_binned$strata_A)
table(df_binned$strata_B)

# mid_lat_flat_relief (32.5° - 49°)
# have vey low fpa and low fvegh !!!!!!!!!
df_mid_flat <- df_binned |>
  filter(strata_B_label == "mid_latitude_flat_relief")
summary(df_mid_flat)

# load coast outline, vector data
coast <- rnaturalearth::ne_coastline(scale = 110, returnclass = "sf")

ggplot(df_binned, aes(x = lon, y = lat, fill = strata_A)) +
  geom_tile() +
  geom_sf(data = coast, colour = 'black', linewidth = 0.1, inherit.aes = FALSE) +
  theme_bw() +
  coord_sf()

ggplot(df_binned, aes(x = lon, y = lat, fill = strata_B)) +
  geom_tile() +
  geom_sf(data = coast, colour = 'black', linewidth = 0.1, inherit.aes = FALSE) +
  theme_bw() +
  coord_sf()

ggplot(df_filt, aes(x = lon, y = lat, fill = strata_A)) +
  geom_tile() +
  geom_sf(data = coast, colour = 'black', linewidth = 0.1, inherit.aes = FALSE) +
  theme_bw() +
  coord_sf()

ggplot(df_filt, aes(x = lon, y = lat, fill = strata_B)) +
  geom_tile() +
  geom_sf(data = coast, colour = 'black', linewidth = 0.1, inherit.aes = FALSE) +
  theme_bw() +
  coord_sf()
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```
```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```
