#' Filter Tiles Containing Land
#'
#' Filters a grid of geographic tiles to retain only those tiles
#' that intersect with land areas, based on a provided land raster layer.
#'
#' @param tile_grid A data.frame generated by `generate_tile_grid()`, containing tile extents.
#' @param land_raster A SpatRaster representing land areas, where land pixels have values (e.g., 1) and non-land pixels are NA.
#' @return A data.frame containing only the tiles from `tile_grid` that intersect with land.
#'
#' @details
#' This function crops the land raster by each tile extent and checks
#' if any non-NA (land) pixels are present. Tiles without any land pixels are excluded.
filter_land_tiles <- function(tile_grid, land_raster) {
  land_tiles <- tile_grid[FALSE, ]  # Initialize empty data frame

  for (i in seq_len(nrow(tile_grid))) {
    extent_i <- ext(tile_grid$xmin[i], tile_grid$xmax[i], tile_grid$ymin[i], tile_grid$ymax[i])

    # Safely crop the land raster to the current tile extent, handle errors
    cropped_tile <- tryCatch(
      crop(land_raster, extent_i),
      error = function(e) NULL
    )

    # Skip if crop failed or returned NULL
    if (is.null(cropped_tile)) next

    pixel_values <- values(cropped_tile)

    # Skip if all values are NA (no land in this tile)
    if (all(is.na(pixel_values))) next

    # If any pixel is non-NA (land present), keep this tile
    if (any(!is.na(pixel_values))) {
      land_tiles <- rbind(land_tiles, tile_grid[i, ])
    }
  }

  return(land_tiles)
}


